DROP DATABASE IF EXISTS movies;

CREATE DATABASE  IF NOT EXISTS movies;

USE movies;

DROP TABLE IF EXISTS movie;

CREATE TABLE IF NOT EXISTS movie(
	movie_id VARCHAR(9) PRIMARY KEY,
	title VARCHAR(100),
	release_year VARCHAR(4),
	rating DECIMAL(2,1),
	image VARCHAR(255)
);

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
	user_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) UNIQUE,
	password VARCHAR(20)
);